name: Publish package

on:
  release:
    types:
      - created

jobs:
  publish:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install Poetry
        uses: abatilo/actions-poetry@v2.2.0

      - name: Setup environment
        run: poetry install

      - name: Build and publish package
        run: poetry publish --build --username __token__ --password ${{ secrets.TOKEN_PYPI }}

      - name: Notify via Slack
        with:
          slack_webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
          pypi_project_name: pysub-parser
        uses: fedecalendino/slack-release-notifier@v1.2.1
